name: Lint
# This is a basic "build it every time" thing


on: [pull_request,push]


jobs:
  build:
    name: matrix
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          version: v1.16
      - run: make build

